package generator

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"forgecli/internal/config"
	"forgecli/internal/model"
)

type Service struct {
	cfg    config.Config
	client model.ChatClient
}

func New(cfg config.Config, client model.ChatClient) *Service {
	return &Service{cfg: cfg, client: client}
}

func (s *Service) GenerateFile(ctx context.Context, prompt, outputPath string) (string, error) {
	if strings.TrimSpace(prompt) == "" {
		return "", fmt.Errorf("prompt is required")
	}
	if strings.TrimSpace(outputPath) == "" {
		return "", fmt.Errorf("output path is required")
	}
	content, err := s.GenerateContent(ctx, prompt, outputPath)
	if err != nil {
		return "", err
	}
	abs, err := filepath.Abs(outputPath)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(abs, []byte(content), 0o644); err != nil {
		return "", err
	}
	return abs, nil
}

func (s *Service) GenerateContent(ctx context.Context, prompt, outputPath string) (string, error) {
	if strings.TrimSpace(prompt) == "" {
		return "", fmt.Errorf("prompt is required")
	}
	if strings.TrimSpace(outputPath) == "" {
		return "", fmt.Errorf("output path is required")
	}
	return s.buildContent(ctx, prompt, outputPath)
}

func (s *Service) GenerateHTML(ctx context.Context, prompt, outputPath string) (string, error) {
	return s.GenerateFile(ctx, prompt, outputPath)
}

func (s *Service) GenerateHTMLContent(ctx context.Context, prompt string) (string, error) {
	return s.GenerateContent(ctx, prompt, "generated.html")
}

func (s *Service) buildContent(ctx context.Context, prompt, outputPath string) (string, error) {
	if s.client != nil {
		if generated, err := s.generateWithModel(ctx, prompt, outputPath); err == nil && strings.TrimSpace(generated) != "" {
			if isUsableGeneratedContent(outputPath, generated) {
				return generated, nil
			}
		}
	}
	return fallbackContent(outputPath, prompt), nil
}

func (s *Service) generateWithModel(ctx context.Context, prompt, outputPath string) (string, error) {
	ext := strings.ToLower(filepath.Ext(outputPath))
	name := filepath.Base(outputPath)
	systemLines := []string{
		"You generate exactly one complete file.",
		"Return file contents only.",
		"Do not use markdown fences.",
		"The output must be ready to save directly to disk.",
		"Target filename: " + name,
		"Target extension: " + ext,
	}
	if ext == ".html" {
		systemLines = append(systemLines,
			"For HTML files, generate a complete runnable page.",
			"Use inline CSS and inline JavaScript when needed.",
			"Do not reference local style.css or script.js files.",
		)
	}
	resp, err := s.client.Complete(ctx, model.ChatRequest{
		Model: s.cfg.Model.Model,
		Messages: []model.Message{
			{Role: "system", Content: strings.Join(systemLines, "\n")},
			{Role: "user", Content: fmt.Sprintf("Generate the file %s for this request:\n%s", name, prompt)},
		},
		Temperature: s.cfg.Model.Temperature,
	})
	if err != nil {
		return "", err
	}
	return stripCodeFence(resp.Message.Content, ext), nil
}

func stripCodeFence(value, ext string) string {
	trimmed := strings.TrimSpace(value)
	if !strings.HasPrefix(trimmed, "```") {
		return trimmed
	}
	trimmed = strings.TrimPrefix(trimmed, "```"+strings.TrimPrefix(ext, "."))
	trimmed = strings.TrimPrefix(trimmed, "```")
	trimmed = strings.TrimSuffix(trimmed, "```")
	return strings.TrimSpace(trimmed)
}

func isUsableGeneratedContent(outputPath, content string) bool {
	trimmed := strings.TrimSpace(content)
	if trimmed == "" || containsMojibake(trimmed) {
		return false
	}
	ext := strings.ToLower(filepath.Ext(outputPath))
	switch ext {
	case ".html":
		lower := strings.ToLower(trimmed)
		return strings.Contains(lower, "<html") && strings.Contains(lower, "</html>")
	case ".json":
		return strings.HasPrefix(trimmed, "{") || strings.HasPrefix(trimmed, "[")
	case ".go":
		return strings.Contains(trimmed, "package ")
	case ".py":
		return len(trimmed) > 0
	case ".js", ".ts", ".jsx", ".tsx", ".css", ".md", ".txt":
		return len(trimmed) > 0
	default:
		return len(trimmed) > 0
	}
}

func containsMojibake(value string) bool {
	markers := []string{"\ufffd", "鐣", "璐", "寮€", "鍒", "銆?"}
	for _, marker := range markers {
		if strings.Contains(value, marker) {
			return true
		}
	}
	return false
}

func fallbackContent(outputPath, prompt string) string {
	ext := strings.ToLower(filepath.Ext(outputPath))
	name := filepath.Base(outputPath)
	switch ext {
	case ".html":
		return genericHTML(name, prompt)
	case ".js":
		return fmt.Sprintf("// Generated by ForgeCLI\n// Request: %s\n\nconsole.log(%q);\n", prompt, prompt)
	case ".ts":
		return fmt.Sprintf("// Generated by ForgeCLI\n// Request: %s\n\nexport function main(): void {\n  console.log(%q);\n}\n\nmain();\n", prompt, prompt)
	case ".py":
		return fmt.Sprintf("\"\"\"Generated by ForgeCLI\nRequest: %s\n\"\"\"\n\n\ndef main() -> None:\n    print(%q)\n\n\nif __name__ == '__main__':\n    main()\n", prompt, prompt)
	case ".go":
		return fmt.Sprintf("package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(%q)\n}\n", prompt)
	case ".md":
		return fmt.Sprintf("# %s\n\nGenerated by ForgeCLI.\n\n## Request\n\n%s\n", strings.TrimSuffix(name, ext), prompt)
	case ".json":
		return fmt.Sprintf("{\n  \"generated_by\": \"forgecli\",\n  \"request\": %q\n}\n", prompt)
	case ".css":
		return fmt.Sprintf("/* Generated by ForgeCLI\n   Request: %s\n*/\n\n:root {\n  --primary: #2563eb;\n  --text: #111827;\n}\n", prompt)
	default:
		return fmt.Sprintf("Generated by ForgeCLI\nRequest: %s\n", prompt)
	}
}

func genericHTML(name, prompt string) string {
	title := strings.TrimSuffix(name, filepath.Ext(name))
	if strings.TrimSpace(title) == "" {
		title = "Generated Page"
	}
	return fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>%s</title>
  <style>
    body { margin:0; font-family:Segoe UI,sans-serif; background:linear-gradient(135deg,#f8f5ef,#e9edf5); color:#1f2937; display:grid; place-items:center; min-height:100vh; }
    .card { width:min(720px,92vw); background:white; border-radius:24px; padding:32px; box-shadow:0 20px 60px rgba(15,23,42,.12); }
    h1 { margin-top:0; font-size:42px; }
    p { line-height:1.7; color:#475569; }
    code { background:#eef2ff; padding:2px 8px; border-radius:999px; }
  </style>
</head>
<body>
  <main class="card">
    <h1>%s</h1>
    <p>This single-file page was generated by ForgeCLI.</p>
    <p>Prompt: <code>%s</code></p>
  </main>
</body>
</html>
`, title, title, escapeHTML(prompt))
}

func escapeHTML(value string) string {
	replacer := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;", "'", "&#39;")
	return replacer.Replace(value)
}
