"""Generated by ForgeCLI
Request: 帮我生成一个 python 脚本，保存成 tools/hi.py，输出 hello from forgecli
"""


def main() -> None:
    print("帮我生成一个 python 脚本，保存成 tools/hi.py，输出 hello from forgecli")


if __name__ == '__main__':
    main()
